<?php

namespace App\Http\Controllers;

use Illuminate\View\View;

class MapController extends Controller
{
    /**
     * Muestra el mapa de ofertas laborales.
     *
     * SOLO FRONTEND: las ofertas son datos mock hardcodeados.
     * No hay consultas a base de datos.
     */
    public function index(): View
    {
        $offers = [
            [
                'id' => 1,
                'title' => 'Desarrollador Full Stack Laravel',
                'company' => 'Concesionaria San Miguel',
                'companyInitials' => 'SM',
                'location' => 'Encarnación, Paraguay',
                'modality' => 'Presencial',
                'contractType' => 'Tiempo completo',
                'shortDescription' => 'Buscamos desarrollador con experiencia en PHP 8.3 y Laravel 12 para unirse a nuestro equipo de tecnología.',
                'fullDescription' => 'Estamos en búsqueda de un Desarrollador Full Stack con sólida experiencia en PHP 8.3 y Laravel 12 para integrarse a nuestro equipo de tecnología. La persona seleccionada será responsable del desarrollo y mantenimiento de aplicaciones web internas, la integración con APIs de terceros y la optimización del rendimiento de los sistemas existentes.',
                'requirements' => ['PHP 8.3+', 'Laravel 12', 'MySQL / PostgreSQL', 'JavaScript', 'Git', 'APIs REST'],
                'salary' => 'Gs. 7.000.000 - 9.000.000',
                'benefits' => 'Seguro médico, capacitaciones continuas, horario flexible, ambiente laboral agradable, oportunidades de crecimiento.',
                'contact' => 'rrhh@sanmiguel.com.py | +595 71 200 300',
                'publishedAt' => 'Hace 2 días',
                'coords' => [-27.3306, -55.8667],
                'image' => 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=1200&h=600&fit=crop',
                'logoUrl' => 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=100&h=100&fit=crop&crop=center',
                'isPrimary' => true,
            ],
            [
                'id' => 2,
                'title' => 'Analista de Sistemas',
                'company' => 'DataCorp S.A.',
                'companyInitials' => 'DC',
                'location' => 'Encarnación, Paraguay',
                'modality' => 'Híbrido',
                'contractType' => 'Tiempo completo',
                'shortDescription' => 'Analista funcional para proyectos de transformación digital.',
                'fullDescription' => 'Buscamos Analista de Sistemas para liderar el relevamiento de requerimientos y la documentación funcional de proyectos de transformación digital.',
                'requirements' => ['Análisis funcional', 'UML', 'SQL', 'Metodologías ágiles', 'Documentación'],
                'salary' => 'Gs. 6.000.000 - 8.000.000',
                'benefits' => 'Seguro médico, bonos por objetivos, capacitación.',
                'contact' => 'contacto@datacorp.com.py',
                'publishedAt' => 'Hace 5 días',
                'coords' => [-27.3256, -55.8600],
                'image' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=600&fit=crop',
                'logoUrl' => null,
                'isPrimary' => false,
            ],
            [
                'id' => 3,
                'title' => 'Soporte Técnico IT',
                'company' => 'Tech Help Paraguay',
                'companyInitials' => 'TH',
                'location' => 'Encarnación, Paraguay',
                'modality' => 'Presencial',
                'contractType' => 'Medio tiempo',
                'shortDescription' => 'Soporte técnico a usuarios internos y externos.',
                'fullDescription' => 'Estamos buscando un Técnico de Soporte para atender consultas y resolver incidencias técnicas de usuarios internos y externos.',
                'requirements' => ['Redes', 'Windows', 'Linux', 'Atención al cliente'],
                'salary' => 'Gs. 3.500.000 - 4.500.000',
                'benefits' => 'Capacitaciones, transporte, buen clima laboral.',
                'contact' => 'soporte@techhelp.com.py',
                'publishedAt' => 'Hace 1 semana',
                'coords' => [-27.3400, -55.8750],
                'image' => 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&h=600&fit=crop',
                'logoUrl' => null,
                'isPrimary' => false,
            ],
            [
                'id' => 4,
                'title' => 'Diseñador UX/UI',
                'company' => 'Creative Studio',
                'companyInitials' => 'CS',
                'location' => 'Encarnación, Paraguay',
                'modality' => 'Remoto',
                'contractType' => 'Freelance',
                'shortDescription' => 'Diseñador con foco en experiencia de usuario.',
                'fullDescription' => 'Buscamos Diseñador UX/UI para crear experiencias digitales memorables.',
                'requirements' => ['Figma', 'Adobe XD', 'Portafolio', 'Design Thinking'],
                'salary' => 'A convenir',
                'benefits' => 'Trabajo 100% remoto, horario flexible, proyectos variados.',
                'contact' => 'hola@creativestudio.com',
                'publishedAt' => 'Hace 3 días',
                'coords' => [-27.3180, -55.8580],
                'image' => 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1200&h=600&fit=crop',
                'logoUrl' => null,
                'isPrimary' => false,
            ],
            [
                'id' => 5,
                'title' => 'Administrador de Base de Datos',
                'company' => 'Banco Regional',
                'companyInitials' => 'BR',
                'location' => 'Encarnación, Paraguay',
                'modality' => 'Presencial',
                'contractType' => 'Tiempo completo',
                'shortDescription' => 'DBA con experiencia en PostgreSQL y alta disponibilidad.',
                'fullDescription' => 'El Banco Regional busca un Administrador de Base de Datos con experiencia en PostgreSQL para gestionar la infraestructura de datos crítica.',
                'requirements' => ['PostgreSQL', 'Replicación', 'Backups', 'Tuning', 'Alta disponibilidad'],
                'salary' => 'Gs. 8.000.000 - 10.000.000',
                'benefits' => 'Seguro médico familiar, bonos anuales, estabilidad laboral.',
                'contact' => 'talento@bancoregional.com.py',
                'publishedAt' => 'Hace 1 día',
                'coords' => [-27.3350, -55.8700],
                'image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop',
                'logoUrl' => null,
                'isPrimary' => false,
            ],
            [
                'id' => 6,
                'title' => 'Desarrollador Mobile Flutter',
                'company' => 'App Factory',
                'companyInitials' => 'AF',
                'location' => 'Encarnación, Paraguay',
                'modality' => 'Remoto',
                'contractType' => 'Tiempo completo',
                'shortDescription' => 'Desarrollo de apps móviles multiplataforma.',
                'fullDescription' => 'App Factory busca un Desarrollador Mobile con experiencia en Flutter para crear aplicaciones móviles innovadoras.',
                'requirements' => ['Flutter', 'Dart', 'Firebase', 'REST APIs', 'Git'],
                'salary' => 'Gs. 6.500.000 - 8.500.000',
                'benefits' => '100% remoto, capacitaciones, equipos modernos.',
                'contact' => 'jobs@appfactory.com',
                'publishedAt' => 'Hace 4 días',
                'coords' => [-27.3280, -55.8800],
                'image' => 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1200&h=600&fit=crop',
                'logoUrl' => null,
                'isPrimary' => false,
            ],
            [
                'id' => 7,
                'title' => 'Ingeniero DevOps',
                'company' => 'Cloud Solutions',
                'companyInitials' => 'CS',
                'location' => 'Encarnación, Paraguay',
                'modality' => 'Híbrido',
                'contractType' => 'Tiempo completo',
                'shortDescription' => 'Automatización de pipelines CI/CD y gestión de infraestructura.',
                'fullDescription' => 'Buscamos Ingeniero DevOps para automatizar procesos de despliegue, gestionar infraestructura en la nube y garantizar la disponibilidad de los servicios.',
                'requirements' => ['Docker', 'Kubernetes', 'AWS', 'Terraform', 'CI/CD'],
                'salary' => 'Gs. 9.000.000 - 12.000.000',
                'benefits' => 'Seguro médico, home office, bonos por desempeño.',
                'contact' => 'rrhh@cloudsolutions.com.py',
                'publishedAt' => 'Hace 6 horas',
                'coords' => [-27.3220, -55.8650],
                'image' => 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=1200&h=600&fit=crop',
                'logoUrl' => null,
                'isPrimary' => false,
            ],
        ];

        return view('map.index', compact('offers'));
    }
}
